DROP TABLESPACE tbs_water_temp INCLUDING CONTENTS AND DATAFILES;
CREATE TEMPORARY TABLESPACE tbs_water_temp
  TEMPFILE '/opt/oracle/oradata/WATER/WATMON/tbs_temp01.dbf' SIZE 100M;

DROP TABLESPACE tbs_water INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE tbs_water
  DATAFILE '/opt/oracle/oradata/WATER/WATMON/data01.dbf' SIZE 1024M
  AUTOEXTEND OFF
  NOLOGGING
  FLASHBACK OFF;

CREATE USER water
  IDENTIFIED BY water
  DEFAULT TABLESPACE tbs_water
  TEMPORARY TABLESPACE tbs_water_temp;

GRANT CONNECT TO water;
GRANT RESOURCE TO water;
GRANT SELECT_CATALOG_ROLE TO water;
GRANT DBA TO water;
